version: '3.8'

services:
  postgresdb:
    image: postgres
    container_name: postgres_c
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: utec
      POSTGRES_DB: micro2 
    ports:
      - "8002:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 

  app:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: springboot_app
    ports:
      - "8082:8082"  
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/micro2 
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: utec
      SPRING_JPA_HIBERNATE_DDL_AUTO: update 

    depends_on:
      - postgresdb 

volumes:
  postgres_data: