version: '3'
services:
  user_api:
    build: ./micro1
    ports:
      - "8001:8001"
    restart: always
    container_name: mysql_c 
    networks:
      - microservices_network

  product_api:
    build: ./micro2
    ports:
      - "8002:8002"
    restart: always
    container_name: postgres_c 
    networks:
      - microservices_network

  orders_api:
    build: ./micro3
    ports:
      - "8003:8003"
    restart: always
    environment:
      DATABASE_URL: "mongo_c" 
    networks:
      - microservices_network

  orquestador:
    build: ./orquestador
    ports:
      - "8004:8004"
    depends_on:
      - user_api
      - product_api
      - orders_api
    restart: always
    environment:
      USERS_MICROSERVICE_URL: "http://user_api:8001"  
      PRODUCTS_MICROSERVICE_URL: "http://product_api:8002" 
      ORDERS_MICROSERVICE_URL: "http://orders_api:8003" 
    networks:
      - microservices_network

networks:
  microservices_network:
    driver: bridge

