services:

  microservice1:
    build: ./micro1
    restart: always
    ports:
      - "8081:8081"

  microservice2:
    build: ./micro2
    container_name: microservice2
    ports:
      - "8082:8082"  
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/micro2 
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: utec
      SPRING_JPA_HIBERNATE_DDL_AUTO: update 

  microservice3:
    build: ./micro3 
    container_name: microservice3
    environment:
      MONGO_URI: mongodb://mongo:27017/micro3
    ports:
      - "8083:8083"
    depends_on:
      - mongo
      - microservice1
      - microservice2
      
  orquestador:
    build: ./orquestador
    container_name: orquestador
    ports:
      - "8084:8084"
    depends_on:
      - microservice1
      - microservice2
      - microservice3

networks:
  ecomecommerce-network:
    driver: bridge
