openapi: 3.0.0
info:
  title: API de Pedidos y Direcciones
  description: API para gestionar pedidos y direcciones
  version: 1.0.0

paths:
  /pedidos:
    get:
      summary: Obtener todos los pedidos
      responses:
        200:
          description: Lista de pedidos
        500:
          description: Error en el servidor
    post:
      summary: Crear un nuevo pedido
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cliente_id:
                  type: string
                productos_ids:
                  type: array
                  items:
                    type: string
                direccion_id:
                  type: string
                fecha_envio:
                  type: string
                  format: date
                metodo_pago:
                  type: string
                total_pago:
                  type: number
                observaciones:
                  type: string
      responses:
        201:
          description: Pedido creado
        400:
          description: Error en la creación
  /pedidos/{id}:
    put:
      summary: Actualizar un pedido
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cliente_id:
                  type: string
                productos_ids:
                  type: array
                  items:
                    type: string
                direccion_id:
                  type: string
                fecha_envio:
                  type: string
                  format: date
                metodo_pago:
                  type: string
                total_pago:
                  type: number
                observaciones:
                  type: string
      responses:
        200:
          description: Pedido actualizado
        400:
          description: Error en la actualización
        404:
          description: Pedido no encontrado
    delete:
      summary: Eliminar un pedido
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Pedido eliminado
        404:
          description: Pedido no encontrado

  /direcciones:
    get:
      summary: Obtener todas las direcciones
      responses:
        200:
          description: Lista de direcciones
        500:
          description: Error en el servidor
    post:
      summary: Crear una nueva dirección
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                calle:
                  type: string
                ciudad:
                  type: string
                estado:
                  type: string
                codigoPostal:
                  type: string
                pais:
                  type: string
      responses:
        201:
          description: Dirección creada
        400:
          description: Error en la creación
  /direcciones/{id}:
    put:
      summary: Actualizar una dirección
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                calle:
                  type: string
                ciudad:
                  type: string
                estado:
                  type: string
                codigoPostal:
                  type: string
                pais:
                  type: string
      responses:
        200:
          description: Dirección actualizada
        400:
          description: Error en la actualización
        404:
          description: Dirección no encontrada
    delete:
      summary: Eliminar una dirección
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Dirección eliminada
        404:
          description: Dirección no encontrada
