version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_c
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    ports:
      - "8083:8083"
    environment:
      MONGO_URI: mongodb://44.217.181.55:27017/micro3
    depends_on:
      - mongo

  microservice2:
    build:
      context: ./micro2
      dockerfile: Dockerfile
    container_name: microservice2
    ports:
      - "8082:8082"
  
  microservice1:
    build:
      context: ./micro1
      dockerfile: Dockerfile
    container_name: microservice1
    ports:
      - "8081:8081"

volumes:
  mongo_data: