version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_c
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    ports:
      - "8083:8083"
    environment:
      MONGO_URI: mongodb://mongo:27017/micro3  # Connection string to MongoDB
    depends_on:
      - mongo

volumes:
  mongo_data: