version: '3.8'
services:
  micro3:
    build: .
    ports:
      - "8003:8003"
    environment:
      - MONGODB_URI=${MONGODB_URI}
    env_file:
      - .env
    networks:
      - microservices-network
networks:
  microservices-network:
    driver: bridge