openapi: 3.0.0
info:
  title: Orquestador API
  description: API para gestionar pedidos que interactúa con microservicios de usuarios, productos y pedidos.
  version: 1.0.0
servers:
  - url: http://localhost:8004
    description: Orchestrator Local Server

paths:
  /api/orders:
    post:
      summary: Crear un pedido
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                cliente_id:
                  type: string
                direccion:
                  type: object
                  properties:
                    calle:
                      type: string
                    ciudad:
                      type: string
                    estado:
                      type: string
                    codigoPostal:
                      type: string
                    pais:
                      type: string
                productos_ids:
                  type: array
                  items:
                    type: string
      responses:
        201:
          description: Pedido creado exitosamente
        400:
          description: Error en la solicitud
        404:
          description: Cliente o productos no encontrados
        500:
          description: Error del servidor
          
    get:
      summary: Obtener todos los pedidos
      responses:
        200:
          description: Lista de pedidos con detalles
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        500:
          description: Error del servidor

  /api/orders/{id}:
    put:
      summary: Modificar un pedido
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID del pedido a modificar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                cliente_id:
                  type: string
                productos_ids:
                  type: array
                  items:
                    type: string
      responses:
        200:
          description: Pedido modificado exitosamente
        403:
          description: No tienes permiso para modificar este pedido
        400:
          description: Uno o más productos están fuera de stock
        500:
          description: Error del servidor
