version: '3.8'

services:
  orchestrator:
    build: ./orchestrator 
    container_name: orchestrator
    ports:
      - "8004:8004"
    networks:
      - micro_net
    environment:
      USERS_MICROSERVICE_URL: "http://18.212.233.214:8001"  
      PRODUCTS_MICROSERVICE_URL: "http://18.212.233.214:8002" 
      ORDERS_MICROSERVICE_URL: "http://18.212.233.214:8003"

networks:
  micro_net:
    driver: bridge
