version: '3.8'

services:
  orchestrator:
    build: ./orchestrator 
    container_name: orchestrator
    ports:
      - "8004:8004"
    networks:
      - micro_net
    environment:
      USERS_MICROSERVICE_URL: "http://LB-Prod-164609483.us-east-1.elb.amazonaws.com:8001"  
      PRODUCTS_MICROSERVICE_URL: "http://LB-Prod-164609483.us-east-1.elb.amazonaws.com:8002" 
      ORDERS_MICROSERVICE_URL: "http://LB-Prod-164609483.us-east-1.elb.amazonaws.com:8003"

networks:
  micro_net:
    driver: bridge
